# docker compose file format 
version: '3' 

services:
  ekho_microservice: 
    build:
      # directory relative to the directory this file lives in
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: ekho_microservice
    # port format - host port : container port
    ports: 
      # JEC: not completely sure on best practices for port mapping yet
      - "3000:443"
    command: node build/server.js
  dummy_microservice: 
    build:
      context: ./dummy-microservice
      dockerfile: Dockerfile.microservice
    container_name: dummy_microservice
    ports: 
      - "3001:443"
    command: node server/server.js