# docker compose file format 
version: '3' 
services:
  test: 
    image: ekhomicroservice/server-dev
    container_name: server-test
    # port format - host port : container port
    ports:
      - "8080:9000"
    command: npm run test
    volumes: 
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules # the node_modeules volume prevents the (potentially) empty node_modules directory from overwriting the one created on the image from running npm install
    depends_on:
      - mongo-test
      - sample-microservice-test

  sample-microservice-test: 
    image: ekhomicroservice/sample-microservice
    ports: 
      - "8000:9001"
    command: node server/server.js
    volumes: 
      - .:/usr/src/app

  mongo-test:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME="${MONGO_INITDB_ROOT_USERNAME}"
      - MONGO_INITDB_ROOT_PASSWORD="${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - test-db-volume:/var/lib/mongodb/data
volumes:
  node_modules:
  test-db-volume:
