# docker compose file format 
version: '3' 
services:
  dev: 
    image: ekhomicroservice/server-dev
    container_name: server-dev-hot
    # port format - host port : container port
    ports: 
      - "8080:8080"
    command: npm run dev
    volumes: 
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules # the node_modeules volume prevents the (potentially) empty node_modules directory from overwriting the one created on the image from running npm install
    depends_on:
      - mongo
      - sample-microservice

  sample-microservice: 
    image: ekhomicroservice/sample-microservice
    ports: 
      - "8000:8000"
    command: node server/server.js
    volumes: 
      - .:/usr/src/app

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME="${MONGO_INITDB_ROOT_USERNAME}"
      - MONGO_INITDB_ROOT_PASSWORD="${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - dev-db-volume:/var/lib/mongodb/data
volumes:
  node_modules:
  dev-db-volume:
